### ISSUE TITLE
Different shard ID for the same web authority

### ISSUE THREAD

**Issue by cgr71ii** [paracrawl/giashard#8]
Hi!

```bash
giashardid https://www.futuremovieshop.fi/index.php?language=en
# 128
giashardid https://www.futuremovieshop.fi/%s
# 46

giashardid -s https://www.futuremovieshop.fi/index.php?language=en
# futuremovieshop
giashardid -s https://www.futuremovieshop.fi/%s
# https:
```

Of all the URLs I processed from www.futuremovieshop.fi, only https://www.futuremovieshop.fi/%s has a different shard ID. It seems that this is due to the '%' symbol, but I am not sure. Is this a bug or is expected behavior?

Thank you!

**Comment by jelmervdl** [comment]
I'd think because it tries to parse `%s` like say `%20` and fails. It then falls back to a regular expression, `^([a-zA-Z0-9][a-zA-Z0-9\-.]*[a-zA-Z0-9]).*`, which is not able to deal with the protocol part.

It was expected behaviour for giawarc at the time since we didn't have the protocol prefix at the time I think in the urls. But all usage now does see complete urls and I'd say this is a bug.
